import { useMemo, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Download, FileSpreadsheet, FileText, Palette } from 'lucide-react';
import AppLayout from '@/components/layout/AppLayout';
import AppHeader from '@/components/layout/AppHeader';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { useProjects, useReportTemplates, useTasks, useTeamMembers, useTickets, useWorkspaceSettings } from '@/hooks/useProjects';
import { toast } from 'sonner';

const tooltipStyle = { background: 'hsl(var(--card))', border: '1px solid hsl(var(--border))', borderRadius: '8px', fontSize: '13px' };

const fontMap: Record<string, string> = {
  inter: 'Inter, system-ui, -apple-system, sans-serif',
  serif: 'Georgia, Times New Roman, serif',
  mono: 'ui-monospace, SFMono-Regular, Menlo, monospace',
  handwritten: 'Comic Sans MS, Bradley Hand, Segoe Print, cursive',
};

const csvEscape = (value: unknown) => `"${String(value ?? '').replace(/"/g, '""')}"`;

const Reports = () => {
  const { data: projects = [] } = useProjects();
  const { data: tasks = [] } = useTasks();
  const { data: teamMembers = [] } = useTeamMembers();
  const { data: tickets = [] } = useTickets();
  const { data: templates = [] } = useReportTemplates();
  const { data: settings } = useWorkspaceSettings();
  const [selectedTemplateId, setSelectedTemplateId] = useState<string>('report-exec');
  const [selectedProjectId, setSelectedProjectId] = useState<string>('all');
  const [reportCadence, setReportCadence] = useState<'daily' | 'weekly' | 'monthly'>('weekly');

  const appearance = (settings?.appearance ?? {}) as any;
  const documentTitle = String(appearance.documentTitle ?? 'PMO Delivery Report');
  const documentFooter = String(appearance.documentFooter ?? 'Generated by PMO Workspace');
  const primaryColor = String(appearance.primaryColor ?? '221 83% 53%');
  const accentColor = String(appearance.accentColor ?? '173 58% 39%');
  const reportFont = String(appearance.fontCss ?? fontMap[appearance.fontFamily] ?? fontMap.inter);
  const reportGradient = `linear-gradient(135deg, hsl(${primaryColor}), hsl(${accentColor}))`;

  const selectedTemplate = templates.find((template) => template.id === selectedTemplateId) ?? templates[0];
  const selectedProject = selectedProjectId === 'all' ? null : projects.find((project) => project.id === selectedProjectId);
  const filteredTasks = selectedProject ? tasks.filter((task) => task.project_id === selectedProject.id || task.projectId === selectedProject.id) : tasks;
  const filteredTickets = selectedProject ? tickets.filter((ticket) => ticket.projectId === selectedProject.id) : tickets;

  const reportRows = useMemo(() => {
    if (!selectedTemplate) return [];

    if (selectedTemplate.focus === 'resource') {
      return teamMembers.map((member) => {
        const aliases = [member.name, member.name.split(' ')[0]];
        const assignedTasks = filteredTasks.filter((task) => aliases.includes(task.assignee) || task.assignee_id === member.id || task.assignees?.includes(member.id));
        const assignedHours = assignedTasks.reduce((sum, task) => sum + (task.workloadHours ?? 0), 0);
        const capacity = member.capacityHours ?? 40;
        return {
          member: member.name,
          capacity,
          assignedHours,
          utilization: `${Math.round((assignedHours / Math.max(1, capacity)) * 100)}%`,
          target: `${member.utilizationTarget ?? 85}%`,
        };
      });
    }

    if (selectedTemplate.focus === 'risk') {
      return (selectedProject ? [selectedProject] : projects).map((project) => {
        const projectTasks = tasks.filter((task) => task.project_id === project.id || task.projectId === project.id);
        const overdueTasks = projectTasks.filter((task) => task.due_date && new Date(task.due_date) < new Date() && task.status !== 'done').length;
        const openTickets = tickets.filter((ticket) => ticket.projectId === project.id && ticket.status !== 'closed').length;
        return {
          project: project.name,
          risk: project.risk_level ?? 'medium',
          overdueTasks,
          openTickets,
        };
      });
    }

    if (selectedTemplate.focus === 'schedule') {
      return (selectedProject ? [selectedProject] : projects).map((project) => {
        const projectTasks = tasks.filter((task) => task.project_id === project.id || task.projectId === project.id);
        const dependencies = projectTasks.reduce((sum, task) => sum + (task.predecessors?.length ?? 0), 0);
        const duration = projectTasks.reduce((sum, task) => sum + (task.workloadHours ?? 0), 0) / 8;
        return {
          project: project.name,
          start: project.start_date ?? project.startDate,
          end: project.end_date ?? project.endDate,
          duration: `${duration || 0}d`,
          dependencies,
        };
      });
    }

    return (selectedProject ? [selectedProject] : projects).map((project) => ({
      project: project.name,
      status: project.status,
      progress: `${project.progress}%`,
      budget: `$${project.budget ?? '0'}`,
      risk: project.risk_level ?? 'medium',
    }));
  }, [filteredTasks, projects, selectedProject, selectedTemplate, tasks, teamMembers, tickets]);

  const chartData = useMemo(() => {
    if (!selectedTemplate) return [];
    if (selectedTemplate.focus === 'resource') {
      return reportRows.map((row) => ({ name: row.member, value: Number.parseInt(String(row.utilization).replace('%', ''), 10) || 0 }));
    }
    if (selectedTemplate.focus === 'risk') {
      return reportRows.map((row) => ({ name: row.project, overdue: row.overdueTasks, tickets: row.openTickets }));
    }
    if (selectedTemplate.focus === 'schedule') {
      return reportRows.map((row) => ({ name: row.project, duration: Number.parseInt(String(row.duration).replace('d', ''), 10) || 0, dependencies: row.dependencies }));
    }
    return reportRows.map((row) => ({ name: row.project, progress: Number.parseInt(String(row.progress).replace('%', ''), 10) || 0 }));
  }, [reportRows, selectedTemplate]);

  const exportSelected = () => {
    if (!selectedTemplate) return;
    const header = selectedTemplate.columns.join(',');
    const rows = reportRows.map((row) => selectedTemplate.columns.map((column) => csvEscape(row[column as keyof typeof row])).join(','));
    const metadata = [
      `# ${documentTitle}`,
      `# Template: ${selectedTemplate.name}`,
      `# Organization: ${settings?.namespace.organization ?? 'Workspace'}`,
      `# Generated: ${new Date().toLocaleString()}`,
      `# Footer: ${documentFooter}`,
      '',
    ].join('\n');
    const blob = new Blob([metadata + [header, ...rows].join('\n')], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `${selectedTemplate.name.toLowerCase().replace(/\s+/g, '-')}-${new Date().toISOString().slice(0, 10)}.csv`;
    anchor.click();
    URL.revokeObjectURL(url);
    toast.success(`${selectedTemplate.name} exported with document branding`);
  };

  const projectStatusReport = useMemo(() => {
    if (!selectedProject) return null;
    const projectTasks = tasks.filter((task) => task.project_id === selectedProject.id || task.projectId === selectedProject.id);
    const completedTasks = projectTasks.filter((task) => task.status === 'done').length;
    const openTickets = tickets.filter((ticket) => ticket.projectId === selectedProject.id && ticket.status !== 'closed').length;
    const totalTimesheetHours = projectTasks.reduce((sum, task) => sum + (task.timesheetEntries ?? []).reduce((hours, entry) => hours + (entry.hours ?? 0), 0), 0);
    const risks = selectedProject.risks ?? [];
    const stakeholders = selectedProject.stakeholders ?? [];
    return {
      title: `${reportCadence[0].toUpperCase()}${reportCadence.slice(1)} Status Report`,
      cadence: reportCadence,
      lines: [
        `Project: ${selectedProject.name}`,
        `Cadence: ${reportCadence}`,
        `Status: ${selectedProject.status}`,
        `Progress: ${selectedProject.progress}%`,
        `Tasks completed: ${completedTasks}/${projectTasks.length}`,
        `Open tickets: ${openTickets}`,
        `Timesheet hours logged: ${totalTimesheetHours}h`,
        `Open risks: ${risks.filter((risk) => risk.status !== 'closed').length}`,
        `Stakeholders tracked: ${stakeholders.length}`,
        `Reporting note: ${selectedProject.projectNature || selectedProject.description || 'Project context not defined.'}`,
      ],
    };
  }, [reportCadence, selectedProject, tasks, tickets]);

  const exportStatusReport = () => {
    if (!projectStatusReport || !selectedProject) return;
    const content = [
      documentTitle,
      `${projectStatusReport.title} - ${settings?.namespace.organization ?? 'Workspace'}`,
      `Generated: ${new Date().toLocaleString()}`,
      ''.padEnd(72, '='),
      ...projectStatusReport.lines,
      ''.padEnd(72, '='),
      documentFooter,
    ].join('\n');
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `${selectedProject.name.toLowerCase().replace(/\s+/g, '-')}-${reportCadence}-status-report.txt`;
    anchor.click();
    URL.revokeObjectURL(url);
    toast.success(`${projectStatusReport.title} exported with branded header`);
  };

  return (
    <AppLayout>
      <AppHeader title="Reports & Exports" subtitle={`${settings?.namespace.organization ?? 'Workspace'} reporting with admin-controlled document branding, colors, and fonts.`} />
      <div className="p-6 space-y-6 animate-fade-in" style={{ fontFamily: reportFont }}>
        <Card className="overflow-hidden border-primary/30 shadow-xl">
          <div className="h-3" style={{ background: reportGradient }} />
          <CardContent className="p-6">
            <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
              <div>
                <div className="flex items-center gap-2">
                  <FileText className="h-5 w-5 text-primary" />
                  <h2 className="text-2xl font-black">{documentTitle}</h2>
                </div>
                <p className="mt-1 text-sm text-muted-foreground">{documentFooter}</p>
                <div className="mt-3 flex flex-wrap gap-2">
                  <Badge variant="secondary"><Palette className="mr-1 h-3 w-3" /> Admin branded</Badge>
                  <Badge variant="outline">Font: {String(appearance.fontFamily ?? 'inter')}</Badge>
                  <Badge variant="outline">Colors from Settings</Badge>
                </div>
              </div>
              <Button variant="outline" onClick={() => window.location.assign('/settings')}>Edit Branding in Settings</Button>
            </div>
          </CardContent>
        </Card>

        <Card className="glass">
          <CardHeader>
            <CardTitle className="text-base">Project Status Report Generator</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex flex-wrap gap-3">
              <Select value={selectedProjectId} onValueChange={setSelectedProjectId}>
                <SelectTrigger className="w-64"><SelectValue placeholder="Select project" /></SelectTrigger>
                <SelectContent><SelectItem value="all">All projects</SelectItem>{projects.map((project) => <SelectItem key={project.id} value={project.id}>{project.name}</SelectItem>)}</SelectContent>
              </Select>
              <Select value={reportCadence} onValueChange={(value: 'daily' | 'weekly' | 'monthly') => setReportCadence(value)}>
                <SelectTrigger className="w-48"><SelectValue placeholder="Cadence" /></SelectTrigger>
                <SelectContent><SelectItem value="daily">Daily</SelectItem><SelectItem value="weekly">Weekly</SelectItem><SelectItem value="monthly">Monthly</SelectItem></SelectContent>
              </Select>
              <Button variant="outline" onClick={exportStatusReport} disabled={!selectedProject}>
                <Download className="h-4 w-4 mr-2" />Export Branded Status Report
              </Button>
            </div>
            {projectStatusReport ? (
              <div className="overflow-hidden rounded-2xl border bg-card">
                <div className="px-4 py-3 text-primary-foreground" style={{ background: reportGradient }}>
                  <p className="font-black">{projectStatusReport.title}</p>
                  <p className="text-xs opacity-90">{selectedProject?.name} · {settings?.namespace.organization ?? 'Workspace'}</p>
                </div>
                <div className="space-y-1 p-4 text-sm text-muted-foreground">
                  {projectStatusReport.lines.map((line) => <p key={line}>{line}</p>)}
                </div>
              </div>
            ) : <p className="text-sm text-muted-foreground">Choose a project to generate a daily, weekly, or monthly status report.</p>}
          </CardContent>
        </Card>

        <div className="flex items-center justify-between gap-3 flex-wrap">
          <div className="flex items-center gap-3">
            <Select value={selectedTemplateId} onValueChange={setSelectedTemplateId}>
              <SelectTrigger className="w-72"><SelectValue placeholder="Choose report template" /></SelectTrigger>
              <SelectContent>{templates.map((template) => <SelectItem key={template.id} value={template.id}>{template.name}</SelectItem>)}</SelectContent>
            </Select>
            {selectedTemplate && <Badge variant="secondary">{selectedTemplate.focus}</Badge>}
          </div>
          <div className="flex gap-2">
            <Button onClick={exportSelected} variant="outline" size="sm"><FileSpreadsheet className="h-4 w-4 mr-2" />Export Branded CSV</Button>
            <Button onClick={() => toast.info('PDF/Word package generation will use the same branding profile in the next document-export package.')} variant="outline" size="sm"><FileText className="h-4 w-4 mr-2" />PDF / Word Branding Ready</Button>
          </div>
        </div>

        {selectedTemplate && <Card className="glass"><CardContent className="p-5"><p className="text-sm font-medium">{selectedTemplate.name}</p><p className="text-xs text-muted-foreground mt-1">{selectedTemplate.description}</p></CardContent></Card>}

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <Card className="glass"><CardHeader><CardTitle className="text-base">Generated Visualization</CardTitle></CardHeader><CardContent><ResponsiveContainer width="100%" height={280}>{selectedTemplate?.focus === 'risk' ? (<BarChart data={chartData}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" /><XAxis dataKey="name" stroke="hsl(var(--muted-foreground))" fontSize={12} /><YAxis stroke="hsl(var(--muted-foreground))" fontSize={12} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="overdue" fill={`hsl(${accentColor})`} radius={[4, 4, 0, 0]} /><Bar dataKey="tickets" fill="hsl(var(--destructive))" radius={[4, 4, 0, 0]} /></BarChart>) : selectedTemplate?.focus === 'schedule' ? (<AreaChart data={chartData}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" /><XAxis dataKey="name" stroke="hsl(var(--muted-foreground))" fontSize={12} /><YAxis stroke="hsl(var(--muted-foreground))" fontSize={12} /><Tooltip contentStyle={tooltipStyle} /><Area type="monotone" dataKey="duration" stroke={`hsl(${primaryColor})`} fill={`hsl(${primaryColor} / 0.15)`} /><Area type="monotone" dataKey="dependencies" stroke={`hsl(${accentColor})`} fill={`hsl(${accentColor} / 0.12)`} /></AreaChart>) : (<BarChart data={chartData}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" /><XAxis dataKey="name" stroke="hsl(var(--muted-foreground))" fontSize={12} /><YAxis stroke="hsl(var(--muted-foreground))" fontSize={12} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey={selectedTemplate?.focus === 'resource' ? 'value' : 'progress'} fill={`hsl(${primaryColor})`} radius={[4, 4, 0, 0]} /></BarChart>)}</ResponsiveContainer></CardContent></Card>

          <Card className="glass"><CardHeader><CardTitle className="text-base">Report Summary</CardTitle></CardHeader><CardContent className="space-y-3">{selectedTemplate?.focus === 'resource' && <><p className="text-sm">Average utilization: {Math.round(reportRows.reduce((sum, row) => sum + (Number.parseInt(String(row.utilization).replace('%', ''), 10) || 0), 0) / Math.max(1, reportRows.length))}%</p><p className="text-sm">Members over target: {reportRows.filter((row) => (Number.parseInt(String(row.utilization).replace('%', ''), 10) || 0) > (Number.parseInt(String(row.target).replace('%', ''), 10) || 0)).length}</p></>}{selectedTemplate?.focus === 'risk' && <><p className="text-sm">Projects with open delivery pressure: {reportRows.filter((row) => row.overdueTasks > 0 || row.openTickets > 0).length}</p><p className="text-sm">Highest risk count: {Math.max(...reportRows.map((row) => row.overdueTasks + row.openTickets), 0)}</p></>}{selectedTemplate?.focus === 'schedule' && <><p className="text-sm">Total planned duration: {reportRows.reduce((sum, row) => sum + (Number.parseInt(String(row.duration).replace('d', ''), 10) || 0), 0)} days</p><p className="text-sm">Tracked dependencies: {reportRows.reduce((sum, row) => sum + (row.dependencies || 0), 0)}</p></>}{selectedTemplate?.focus === 'executive' && <><p className="text-sm">Active portfolios: {projects.filter((project) => project.status === 'active').length}</p><p className="text-sm">Average progress: {Math.round(projects.reduce((sum, project) => sum + project.progress, 0) / Math.max(1, projects.length))}%</p></>}</CardContent></Card>
        </div>

        <Card className="glass overflow-hidden"><div className="h-2" style={{ background: reportGradient }} /><CardHeader><CardTitle className="text-base">Generated Data Table</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-left border-collapse"><thead className="border-b bg-muted/20"><tr>{selectedTemplate?.columns.map((column) => <th key={column} className="p-3 text-xs font-black uppercase tracking-widest">{column}</th>)}</tr></thead><tbody>{reportRows.map((row, index) => <tr key={`${selectedTemplateId}-${index}`} className="border-b">{selectedTemplate?.columns.map((column) => <td key={column} className="p-3 text-sm">{String(row[column as keyof typeof row] ?? '-')}</td>)}</tr>)}</tbody></table></CardContent></Card>
      </div>
    </AppLayout>
  );
};

export default Reports;
