// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim();
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim();
const SUPABASE_PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID?.trim() || null;
const LINKED_SUPABASE_PROJECT_REF = __SUPABASE_LINKED_PROJECT_REF__?.trim() || null;

const decodeBase64Url = (value: string) => {
  const normalized = value.replace(/-/g, "+").replace(/_/g, "/");
  const padding = normalized.length % 4 === 0 ? "" : "=".repeat(4 - (normalized.length % 4));
  return atob(`${normalized}${padding}`);
};

const extractProjectRefFromUrl = (url?: string | null) => {
  if (!url) return null;

  try {
    const hostname = new URL(url).hostname;
    const projectRef = hostname.split(".")[0]?.trim();
    return projectRef || null;
  } catch {
    return null;
  }
};

const extractProjectRefFromKey = (key?: string | null) => {
  if (!key) return null;

  const parts = key.split(".");
  if (parts.length < 2) return null;

  try {
    const payload = JSON.parse(decodeBase64Url(parts[1])) as { ref?: unknown };
    return typeof payload.ref === "string" && payload.ref.trim() ? payload.ref.trim() : null;
  } catch {
    return null;
  }
};

const SUPABASE_URL_PROJECT_REF = extractProjectRefFromUrl(SUPABASE_URL);
const SUPABASE_KEY_PROJECT_REF = extractProjectRefFromKey(SUPABASE_PUBLISHABLE_KEY);
const hasSupabaseEnv = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
const activeSupabaseProjectRef =
  SUPABASE_PROJECT_ID ?? SUPABASE_URL_PROJECT_REF ?? SUPABASE_KEY_PROJECT_REF ?? null;

const supabaseConfigIssues: string[] = [];

if (!hasSupabaseEnv) {
  supabaseConfigIssues.push(
    "Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. Running in local-only mode until configured.",
  );
}

if (SUPABASE_PROJECT_ID && SUPABASE_URL_PROJECT_REF && SUPABASE_PROJECT_ID !== SUPABASE_URL_PROJECT_REF) {
  supabaseConfigIssues.push(
    `VITE_SUPABASE_PROJECT_ID (${SUPABASE_PROJECT_ID}) does not match the Supabase URL project ref (${SUPABASE_URL_PROJECT_REF}).`,
  );
}

if (SUPABASE_PROJECT_ID && SUPABASE_KEY_PROJECT_REF && SUPABASE_PROJECT_ID !== SUPABASE_KEY_PROJECT_REF) {
  supabaseConfigIssues.push(
    `VITE_SUPABASE_PROJECT_ID (${SUPABASE_PROJECT_ID}) does not match the publishable key project ref (${SUPABASE_KEY_PROJECT_REF}).`,
  );
}

if (SUPABASE_URL_PROJECT_REF && SUPABASE_KEY_PROJECT_REF && SUPABASE_URL_PROJECT_REF !== SUPABASE_KEY_PROJECT_REF) {
  supabaseConfigIssues.push(
    `VITE_SUPABASE_URL points to ${SUPABASE_URL_PROJECT_REF}, but VITE_SUPABASE_PUBLISHABLE_KEY belongs to ${SUPABASE_KEY_PROJECT_REF}.`,
  );
}

if (
  LINKED_SUPABASE_PROJECT_REF &&
  activeSupabaseProjectRef &&
  LINKED_SUPABASE_PROJECT_REF !== activeSupabaseProjectRef
) {
  supabaseConfigIssues.push(
    `This workspace is linked to Supabase project ${LINKED_SUPABASE_PROJECT_REF}, but the app is configured for ${activeSupabaseProjectRef}. Update VITE_SUPABASE_URL, VITE_SUPABASE_PROJECT_ID, and VITE_SUPABASE_PUBLISHABLE_KEY to the linked project.`,
  );
}

const supabaseOperational = hasSupabaseEnv && supabaseConfigIssues.length === 0;

type AuthStorageAdapter = {
  getItem: (key: string) => string | null;
  removeItem: (key: string) => void;
  setItem: (key: string, value: string) => void;
};

type SupabaseLockFunction = <R>(name: string, acquireTimeout: number, fn: () => Promise<R>) => Promise<R>;

const createMemoryStorage = (): AuthStorageAdapter => {
  const store = new Map<string, string>();

  return {
    getItem: (key) => store.get(key) ?? null,
    removeItem: (key) => {
      store.delete(key);
    },
    setItem: (key, value) => {
      store.set(key, value);
    },
  };
};

const canUseStorage = (storage: Storage) => {
  try {
    const testKey = "__supabase_storage_check__";
    storage.setItem(testKey, "1");
    storage.removeItem(testKey);
    return true;
  } catch {
    return false;
  }
};

const createAuthStorage = (): AuthStorageAdapter => {
  if (typeof window === "undefined") {
    return createMemoryStorage();
  }

  if (canUseStorage(window.localStorage)) {
    return window.localStorage;
  }

  if (canUseStorage(window.sessionStorage)) {
    console.warn("[supabase] localStorage unavailable, using sessionStorage for auth.");
    return window.sessionStorage;
  }

  console.warn("[supabase] localStorage and sessionStorage unavailable, using in-memory auth storage.");
  return createMemoryStorage();
};

const createTabSafeSupabaseLock = (): SupabaseLockFunction => {
  let chain = Promise.resolve();

  return async <R,>(_name: string, _acquireTimeout: number, fn: () => Promise<R>) => {
    const previous = chain.catch(() => undefined);
    let releaseCurrent: () => void = () => undefined;
    chain = previous.then(() => new Promise<void>((resolve) => {
      releaseCurrent = resolve;
    }));

    await previous;

    try {
      return await fn();
    } finally {
      releaseCurrent();
    }
  };
};

const authStorage = createAuthStorage();
const authLock = createTabSafeSupabaseLock();

export type SupabaseConfigStatus = {
  activeProjectRef: string | null;
  envProjectRef: string | null;
  hasEnv: boolean;
  isOperational: boolean;
  issues: string[];
  keyProjectRef: string | null;
  linkedProjectRef: string | null;
  urlProjectRef: string | null;
};

export const getSupabaseConfigStatus = (): SupabaseConfigStatus => ({
  activeProjectRef: activeSupabaseProjectRef,
  envProjectRef: SUPABASE_PROJECT_ID,
  hasEnv: hasSupabaseEnv,
  isOperational: supabaseOperational,
  issues: [...supabaseConfigIssues],
  keyProjectRef: SUPABASE_KEY_PROJECT_REF,
  linkedProjectRef: LINKED_SUPABASE_PROJECT_REF,
  urlProjectRef: SUPABASE_URL_PROJECT_REF,
});

export const isSupabaseOperational = () => supabaseOperational;
export const getPrimarySupabaseConfigIssue = () => supabaseConfigIssues[0] ?? null;

if (supabaseConfigIssues.length > 0) {
  console.warn("[supabase]", supabaseConfigIssues.join(" "));
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  supabaseOperational ? SUPABASE_URL! : "https://placeholder.supabase.co",
  supabaseOperational ? SUPABASE_PUBLISHABLE_KEY! : "placeholder-anon-key",
  {
    auth: {
      storage: authStorage,
      persistSession: true,
      autoRefreshToken: true,
      lock: authLock,
    },
  },
);
